- leveldb/table/reader.go
- leveldb/table/writer.go
The Snappy path has recently changed: https://github.com/golang/snappy/issues/12
This PR updates the imports in `reader.go` and `writer.go` respectively.
> Update Snappy imports to use new canonical path

- leveldb/db_write.go
This PR fixes a logical race reported in https://github.com/syndtr/goleveldb/issues/136.
The database writes in the current code are optimized, so that if multiple ones are pending, they are aggregated into a mega batch, written out as a single operation and then all of the individual writes acked at once.
The race is in the termination part of the write, where the writer goroutine first released the write lock, and only then acked the merged writes. This leaves a small gap open for a new write to begin, and that new write itself to accumulate merges of its own. The issue is then that the initial writer will acknowledge merges other than its own, leading to unfinished writes being signaled as done.
The fix is to move the acks before releasing the write lock, essentially exhausting all of …
> Ack existing writes before accepting new ones

- leveldb/storage/file_storage_nacl.go
This change makes leveldb compile and work in Native Client.
All file system functions return syscall.ENOTSUP because nacl has
no file system.
> storage: fix compilation with GOOS=nacl

- leveldb/storage/file_storage_plan9.go
The workaround for rename introduced with
45d424a47028cb8fd1bea3f4814d489a6a6db525 is no longer needed/valid.
Since commit 16dcef80d46d78cc198bfc680e9cf05cea9095cc (December 2013)
in golang/go repository os.Rename was changed to accept (and expect) a
full path for new path (albeit the file should be in the same
directory).
> Fixed rename on plan 9 (invalid argument error).

- leveldb/storage/mem_storage.go
- leveldb/storage/mem_storage_test.go
The `typeShift` constant used in `storage.NewMemStorage` doesn't cover all of the states, so the `List` method returns invalid `FileDesc` values.
Further, the `Rename` method for in-memory storage doesn't work since it requires both the new and old filename to be _invalid_, rather than requiring them both to be valid.
This change tests for and fixes both bugs.
> leveldb/storage: correct FileType masking and Rename in MemStorage

- leveldb/storage/file_storage.go
increase fs.logSize when writing in LOG file.
issue: https://github.com/syndtr/goleveldb/issues/216
> Update log file size in fileStore.doLog method

- leveldb/db.go
- leveldb/db_write.go
In this PR, introduces a new flag `WritePaused`.
Currently we expose `WriteDelayN` and `WriteDelay` statistic to outer, so that external user can  know that the system is performing compaction and all write operations will be paused.
**But these two statistics will be added only after the long compaction finished**, so that external user doesn't know what happened to leveldb during this long procedure.
The `WritePaused` flag can notify external user that the long compaction has begun and all writes will be suspended for a period of time
> leveldb: add write paused flag

- leveldb/storage/file_storage_unix.go
In go 1.8, various functions were updated to return PathError instead.
This includes `os.File Sync()`.
For reference, the upstream commit which made this change is
https://github.com/golang/go/commit/212d2f82e05.
Arguably we could take this as a signal that upstream doesn't consider
this error type stable, so rather than attempt to identify it we could
assume any error from Sync should be ignored, but I think there's some
amount of value still in trying to error out on things like ENOSPACE or
EBADF.
This should re-fix #103 and fix the perkeep issue https://github.com/perkeep/perkeep/issues/1185
> leveldb/storage: catch EINVAL on go >= 1.8 too

- leveldb/db_compaction.go
Currently write operations will be paused if there are too many level0 files. However once enough level0 files be compacted the write operation should be resumed, otherwise the database can be sucked until all compactions be finished.
> leveldb: resume write operation asap

- leveldb/iterator/iter.go
Just a small rewording to make the docstring for the iterator's `Prev()` and `Next()` methods clearer.
The current formulation...
> It returns whether the iterator is exhausted.
...suggests that eg. `Next()` would return `true` when the iterator is exhausted.
> Update docs for iterator Prev / Next to be unambiguous.

- go.mod
- go.sum
In particular, update snappy to the now-released module version v0.0.1.  The
rest of the changes are ancillary updates from the Go tool, and do not change
the versions selected.
> Update the snappy module dependency.

- leveldb/db.go
- leveldb/db_compaction.go
- leveldb/db_test.go
- leveldb/db_transaction.go
- leveldb/session.go
- leveldb/table.go
- leveldb/version.go
- leveldb/version_test.go
This PR introduces a bypass for quick version finalization.
For more context, checkout [go-ethereum issue](https://github.com/ethereum/go-ethereum/issues/17020#issuecomment-465474674)
We use leveldb as the storage engine in go-ethereum project. While people always complain about the long compaction pause for archive node(this type of node can have more than 1TB data now).
After some investigations, I found during the long compaction pause, almost I/O is idle while one CPU core is always full. And also from the [pperf information](https://drive.google.com/open?id=1VrkabzHa09fhgxmV8PTO4nikfs6xMrkn) from @karalabe, we can notice most of the time is spent on the bytes compare.
Finally I realize when the database size grow, the number of files per level also grow. In the go-ethereum project, …
> leveldb: introduce trivial version finalization

- leveldb/db.go
Use the `Sizes` object in `Stats` so the caller can call `Sizes.Sum()`. This would break existing callers so maybe better left as is, but thought it might be nice to wrap with a type. What do you think?
> Use Sizes in Stats

- leveldb/version.go
This PR includes a small fix for compaction commit.
For the delete-only level, we can just remove specified files from the base level and then use it as the new version. No qsort needed.
> leveldb: skip resort for delete only level

- leveldb/session_compaction.go
- leveldb/table.go
- leveldb/table_test.go
This PR introduce an optimization for `getOverlaps` function.
In the original implementation, it will traverse all files to find the overlapped file. It is the only approach for level0 since the files are overlapped. While for non-zero files, we can use binary search as the replacement.
> leveldb: optimize getOverlap by binary search

- leveldb/corrupt_test.go
- leveldb/session.go
- leveldb/session_util.go
- leveldb/table.go
- leveldb/version.go
- leveldb/version_test.go
This PR introduces an efficient approach for table file reference.
The original for file reference is:
* When the database version is first time created, then references all relative table files by increasing file ref by 1
* When the version is released(no operation hold the version), deferences all  table files by decreasing file ref by 1
If the database size is 1TB with each file size is 2MB, image the cost for 500,000 file reference cost.
And worse, the read operation(also iterator) will also acquire a version before reading. And it has **very high possibility** then this read operation is the last thing holding the version, it means the cost of huge file deferences is distributed to the read operation. **It will definitely slow down the entire system**.
Therefore I introduce an …
> leveldb: make heavy version reference asynchronous

- leveldb/db.go
we get LevelTablesCounts = [65,34], seems L0 file num is 65
after reopen db,  LevelTablesCounts = [1,65,34]
the origin LevelTablesCounts should be [0,65,34]
if it skip some level, we have no any ideal what the Stat we get really
means
> db.go: Don't skip some level for Stat

- leveldb/db_snapshot.go
The snapshot has a mutex and a `released` bool, but the access methods
touch `db` before looking at `released`. The `db` is set to nil when the
snap is released. Hence ErrSnapshotReleased is never returned, instead
the program panics with a nil deref.
> leveldb: Don't crash when using a released snapshot

- leveldb/util/buffer.go
- leveldb/util/buffer_test.go
Hi @syndtr ,
I merge a lot of optimize from bytes.Buffer, e.g.:
https://github.com/golang/go/commit/55310403ddf051634fa398b4c9e6013d530753f5
https://github.com/golang/go/commit/c08ac36761d3dc03d0a0b0ffb240c4a7c524536b
https://github.com/golang/go/commit/1ba4556a2c84f552f7c9697ad7323fd6cdbc6970
```
name                       old time/op   new time/op   delta
WriteByte-4                 22.9µs ± 2%   14.8µs ± 1%  -35.54%  (p=0.008 n=5+5)
Alloc-4                     22.5µs ± 1%   18.8µs ± 0%  -16.23%  (p=0.004 n=5+6)
BufferNotEmptyWriteRead-4    276µs ± 2%    301µs ± 3%   +8.97%  (p=0.004 n=5+6)
BufferFullSmallReads-4      73.2µs ±24%   63.3µs ± 3%  -13.49%  (p=0.002 n=6+6)
name                       old speed     new speed     delta
WriteByte-4                179MB/s ± 2%  277MB/s ± 1% …
```
> Merge a lot of optimize from bytes.Buffer

- leveldb/storage/file_storage_windows.go
Closes #306 
Originally addressed by PR #315 but this fix feels more correct
This fix also allows all tests to pass on Windows.
> Fix failure to open locked DB in read-only mode on Windows

- leveldb/session_compaction.go
using binary search to find next table
> leveldb: optimize pickCompaction

- .travis.yml
- leveldb/session_util.go
This simple PR adds an fsync call on the manifest file when a new
manifest file is generated at the start.
In absence of this, the code updates the "CURRENT" and deletes the
previous manifest file and a crash at this point could leave the latest
manifest with a single incomplete record. With this content in the manifest file,
a restart is expected to lead to [manifest corrupt error](https://github.com/syndtr/goleveldb/blob/5c35d600f0caac04c20d52438103f1a7aa612598/leveldb/session.go#L192)
This seems to explain the error observed in issue #335. We too have observed this error in our environment.
closes #335.
> Add fsync after creating new manifest

- leveldb/db.go
- leveldb/db_compaction.go
- leveldb/db_test.go
- leveldb/table.go
- leveldb/table/table_test.go
- leveldb/table/writer.go
- leveldb/util/buffer_pool.go
This PR addresses the problem of too much memory being allocated by goleveldb in the project I'm working on here: https://github.com/mit-dci/utcd.
I've conducted two benchmarks to check that this PR lessen the memory allocated:
1: pprof results from the project I'm working on.
2: Benchstat results from the existing benchmark tests in goleveldb.
The project I'm working on is a Bitcoin node in Go. It uses goleveldb to keep track of Bitcoins that are available to be spent. The load on goleveldb is very intense with there being many reads and writes when it first starts up. I used this command to create a controlled test for profiling the memory usage. 
```
timeout -s SIGINT 20m ./btcd --logdir=. --datadir=. --memprofile=memprof-new-goleveldb --connect=127.0.0.1
```
The binary used was …
> util/buffer_pool, db: Reduce memory allocation

- leveldb/db_compaction.go
- leveldb/db_test.go
- leveldb/db_transaction.go
- leveldb/session_compaction.go
- leveldb/session_util.go
- leveldb/util.go
- leveldb/version.go
Most calls already happen with `int64` instances, so this change reduces
one type conversion. On 32-bit arch, converting int64 -> int is lossy
and results in incorrect values being print for levels > 2GiB.
> util: Switch shortenb/sshortenb to int64
